version: '3.8'

services:
  # LocalStack for S3 and SQS
  localstack:
    image: localstack/localstack:latest
    container_name: incident-analyzer-localstack-test
    ports:
      - "14566:4566"
    environment:
      - SERVICES=s3,sqs
      - DEBUG=1
      - DATA_DIR=/var/lib/localstack
      - PERSISTENCE=1
      - DEFAULT_REGION=us-east-1
    volumes:
      - "./localstack/volume:/var/lib/localstack"
      - "./localstack/init-sqs.sh:/etc/localstack/init/ready.d/init-sqs.sh"
    networks:
      - test-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 5s
      timeout: 5s
      retries: 10

  # Incident Log Analyzer
  incident-analyzer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: incident-log-analyzer-test
    environment:
      # AWS Bedrock
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=us-east-1
      - BEDROCK_REGION=us-east-1
      - BEDROCK_MODEL_ID=us.anthropic.claude-3-5-sonnet-20241022-v2:0
      
      # SigNoz
      - SIGNOZ_API_ENDPOINT=${SIGNOZ_API_ENDPOINT}
      - SIGNOZ_API_KEY=${SIGNOZ_API_KEY}
      
      # S3 (LocalStack)
      - S3_BUCKET_NAME=incident-logs-test
      - USE_LOCALSTACK=true
      - LOCALSTACK_ENDPOINT=http://localstack:4566
      
      # SQS (LocalStack)
      - SQS_ENABLED=true
      - SQS_INPUT_QUEUE_URL=http://localstack:4566/000000000000/incident-input-queue
      - SQS_OUTPUT_QUEUE_URL=http://localstack:4566/000000000000/incident-output-queue
      - SQS_POLL_INTERVAL=20
      # SQS_MAX_EMPTY_POLLS not set = infinite polling (continuous)
      
      # Application
      - LOG_LEVEL=INFO
      - LOG_FORMAT=human
      - PYTHONUNBUFFERED=1
    volumes:
      - ./output:/app/output
      - ./tests/test_data:/app/test_data
      - ./performance_reports:/app/performance_reports
    networks:
      - test-network
    depends_on:
      localstack:
        condition: service_healthy
    command: >
      sh -c "
        echo 'Waiting for LocalStack...' &&
        sleep 10 &&
        python -m src.main
      "

networks:
  test-network:
    driver: bridge
